project_id = "cshrensaapqwwxtrztfd"

[functions.sync-planning-center]
verify_jwt = false

[functions.search-planning-center-people]
verify_jwt = false

[functions.get-planning-center-person]
verify_jwt = false
