project_id = "cshrensaapqwwxtrztfd"

[functions.sync-planning-center]
verify_jwt = false

[functions.sync-planning-center-auto]
verify_jwt = false

[functions.search-planning-center-people]
verify_jwt = false

[functions.get-planning-center-person]
verify_jwt = false

[functions.planning-center-auth]
verify_jwt = false

[functions.planning-center-callback]
verify_jwt = false

[functions.create-volunteer-qrcode]
verify_jwt = false

[functions.sync-planning-center-historical]
verify_jwt = false
